### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fatlazycat** [ensime/ensime-gradle#17]
Trying to start an ensime server with a gradle generated .ensime from the 2.2 plugin gives

```
13:15:40.521 ERROR ActorSystem(ENSIME) a.a.ActorSystemImpl - Uncaught fatal error from thread [ENSIME-akka.actor.default-dispatcher-11] shutting down ActorSystem [ENSIME]
java.lang.NoSuchMethodError: org.ensime.core.RichPresentationCompiler.askLoadedTyped(Lscala/reflect/internal/util/SourceFile;ZLscala/tools/nsc/interactive/Response;)V
	at org.ensime.core.RichCompilerControl$class.askLoadedTyped(RichPresentationCompiler.scala:153) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RichPresentationCompiler.askLoadedTyped(RichPresentationCompiler.scala:254) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:241) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:155) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.3.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.3.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.3.jar:na]
	at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:152) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33) ~[scala-library-2.10.3.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.3.jar:na]
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25) ~[scala-library-2.10.3.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.10-2.3.14.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118) ~[scala-library-2.10.3.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.10-2.3.14.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.14.jar:na]
	at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:42) ~[core_2.10-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.14.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.3.jar:na]
```

With a .ensime from a hand crufted sbt file it's fine.

**Comment by fommil** [comment]
I'm afraid this doesn't tell us much. Can you reproduce on a minimal project on github, and let us know which client you're using?

**Comment by fatlazycat** [comment]
Sure will, do. By client I assume it's ensime-emacs ?

**Comment by fommil** [comment]
yeah.

**Comment by coacoas** [comment]
Posting the gradle .ensime and sbt .ensime files would help, as well.  Can you create a gist with those files?

**Comment by fommil** [comment]
this is what we ideally like to see on the emacs side https://github.com/ensime/ensime-emacs/wiki/issue

**Comment by fatlazycat** [comment]
back at work, will knock up a sample and send it over, thanks

**Comment by coacoas** [comment]
Has there been any more discovery on this issue?

**Comment by fatlazycat** [comment]
Sorry no, having issue trying to reproduce it without the company source code.

**Comment by fommil** [comment]
looks like a scala version thing. On ensime-server we aggressively close tickets without a reproduction case :stuck_out_tongue_winking_eye:

**Comment by fatlazycat** [comment]
Sure if I can get a test case separate from our source tree will open again.
