### ISSUE TITLE
unable to build task ensime

### ISSUE THREAD

**Issue by raghuramos1987** [ensime/ensime-gradle#61]
Trying to build the .ensime folder results in the following exception.

`
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: groovy.lang.MissingPropertyException: No such property: file for class: org.gradle.api.internal.artifacts.result.DefaultUnresolvedArtifactResult
Possible solutions: type, failure
        at net.coacoas.gradle.plugins.SubprojectModule$_getReferenceSourceRoots_closure9.doCall(SubprojectModule.groovy:77)
        at net.coacoas.gradle.plugins.SubprojectModule.getReferenceSourceRoots(SubprojectModule.groovy:76)
        at net.coacoas.gradle.plugins.SubprojectModule$getReferenceSourceRoots$0.callCurrent(Unknown Source)
        at net.coacoas.gradle.plugins.SubprojectModule.settings(SubprojectModule.groovy:106)
        at net.coacoas.gradle.plugins.SubprojectModule$settings.call(Unknown Source)
        at net.coacoas.gradle.plugins.EnsimeTask$_writeFile_closure1$_closure6$_closure8.doCall(EnsimeTask.groovy:86)
        at net.coacoas.gradle.plugins.EnsimeTask$_writeFile_closure1$_closure6.doCall(EnsimeTask.groovy:83)
        at net.coacoas.gradle.plugins.EnsimeTask$_writeFile_closure1.doCall(EnsimeTask.groovy:25)
        at net.coacoas.gradle.plugins.EnsimeTask.writeFile(EnsimeTask.groovy:24)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
`

**Comment by raghuramos1987** [comment]
I'll write up something. The current project is too big for me to share here. I'll get back to this in sometime.

**Comment by coacoas** [comment]
Thanks, I appreciate that.

**Comment by raghuramos1987** [comment]
Closing the loop on this. Switching to the snapshot version built the project successfully. thanks @coacoas ! I do have a different issue now which I'll open in a separate bug since it seems more ensime-vim related.
